'\nclass vs instance variables\nmagic / dunder methods\ntight coupling and loose coupling\n'

In [2]:
sales = [12000, 15000, 11000, 10000, 17000]
total = 0
for s in sales:
  total += s
average = total / len(sales)
print(total, average)

65000 13000.0


In [3]:
taxed_sale = []
for s in sales:
  taxed_sale.append(s * 1.10)
print(taxed_sale)

[13200.000000000002, 16500.0, 12100.000000000002, 11000.0, 18700.0]


In [4]:
sales * 1.10

TypeError: can't multiply sequence by non-int of type 'float'

In [5]:
[12000,15000] * 2

[12000, 15000, 12000, 15000]

In [6]:
sales_2024 = [12000, 15000, 11000]
sales_2025 = [13000, 16000, 15000]

In [7]:
import numpy as np
sales = np.array([12000, 15000, 11000, 10000, 17000])

In [8]:
sales

array([12000, 15000, 11000, 10000, 17000])

In [12]:
sales * 1.1

array([13200., 16500., 12100., 11000., 18700.])

In [13]:
sales * 2

array([24000, 30000, 22000, 20000, 34000])

In [14]:
sales

array([12000, 15000, 11000, 10000, 17000])

In [15]:
a = sales * 1.1
a

array([13200., 16500., 12100., 11000., 18700.])

In [16]:
a

array([13200., 16500., 12100., 11000., 18700.])

In [17]:
sales_2024 = np.array([12000, 15000, 11000])
sales_2025 = np.array([13000, 16000, 15000])

sales_2025-sales_2024

array([1000, 1000, 4000])

convert a list of temperatures to numpy

increase all the values by 5% and save in a new array

subtract two numpy arrays



In [27]:
arr1 = np.array([36,55,24,29,41])


In [28]:
arr2 = arr1 * 1.05
arr2

array([37.8 , 57.75, 25.2 , 30.45, 43.05])

In [29]:
arr2 - arr1

array([1.8 , 2.75, 1.2 , 1.45, 2.05])

In [30]:
a = np.array([1,2,3,4])
b = np.array([1,6,3.3,5.2])


In [32]:
a.dtype

dtype('int64')

In [33]:
b.dtype

dtype('float64')

In [34]:
b

array([1. , 6. , 3.3, 5.2])

In [39]:
c = np.array([True, 'a', 1, 2.2])
c.dtype
c

array(['True', 'a', '1', '2.2'], dtype='<U32')

In [40]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [44]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])
a.shape

(2, 4)

In [45]:
a.ndim

2

In [46]:
a.size

8

In [48]:
data = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]])
    #find shape, size, dimensions

In [52]:
#from array (data) find 25 using slicing
print(data[1][1])

25


In [53]:
#from array (data) extract 3rd row using slicing
data[2]

array([35, 40, 45])

In [54]:
arr = np.array([10,20,30])
print(arr+5)
print(arr-3)
print(arr**2)

[15 25 35]
[ 7 17 27]
[100 400 900]


In [55]:
arr2 = np.array([1,2,3])

In [56]:
a + b

array([[ 2. ,  8. ,  6.3,  9.2],
       [ 6. , 12. , 10.3, 13.2]])