In [14]:
import numpy as np
scores = np.array([45, 67, 89, 34, 72, 90, 55])

In [3]:
scores >= 60 #Boolean Mask

array([False,  True,  True, False,  True,  True, False])

In [5]:
scores[scores>=60]

array([67, 89, 72, 90])

In [6]:
ages = np.array([12, 18, 25, 16, 40, 30])
# print ages >= 18
# print ages < 18
# count how many adults
print(ages[ages >= 18])
print(ages[ages<18])
print(len(ages[ages>=18]))

[18 25 40 30]
[12 16]
4


In [15]:
# give 5 bonus marks to students scoring <= 50 (scores array)
scores[scores <= 50 ] += 5
scores

array([50, 67, 89, 39, 72, 90, 55])

In [16]:
marks = np.array([40, 55, 70, 35, 90, 48])

In [17]:
#Add 10 to marks of students below 50
# reduce 5 marks from students above 80
marks[marks<50] += 10 #marks[marks<50] = marks[marks<50] + 10
print(marks)
marks[marks>80] -= 5
print(marks)

[50 55 70 45 90 58]
[50 55 70 45 85 58]


In [19]:
(scores >= 50) & (scores < 80) # (and &) (or |) (not ~) in numpy

array([ True,  True, False, False,  True, False,  True])

In [20]:
scores[(scores >= 50) & (scores < 80)]

array([50, 67, 72, 55])

In [24]:
salary = np.array([20000,35000,50000,80000,120000])
#Find salaries between 30k and 80k
#FInd saalaries above 100k
print(salary[(salary>30000)&(salary<80000)])
print(salary[salary>100000])

[35000 50000]
[120000]


In [27]:
prices = np.array([500,1200,800,1500])
tax = 0.1
#apply tax on prices
#apply 20% discount
print(prices + (prices * tax))


[ 550. 1320.  880. 1650.]


In [28]:
print(prices - prices * 0.2)


[ 400.  960.  640. 1200.]


In [31]:
sales = np.array([[100,200,300],
                  [150,250,450],
                  [200,300,400]]) #rows = days, columns = products

In [32]:
# find sales of first day
sales[0]

array([100, 200, 300])

In [35]:
# all sales of product 2
sales[:,1] #[row,column]

array([200, 250, 300])

In [36]:
# all sales of product 1
sales[:,0]

array([100, 150, 200])

In [37]:
# increase all sales by 10%
sales * 1.1

array([[110., 220., 330.],
       [165., 275., 495.],
       [220., 330., 440.]])

In [39]:
#total sales per product
np.sum(sales, axis=0) #axis = 0 for column-wise operation

array([ 450,  750, 1150])

In [40]:
#total sales per day
np.sum(sales, axis=1)# axis = 1 for row-wise operation

array([600, 850, 900])

In [42]:
#maximum sales value
print(np.max(sales))

450


In [43]:
temperatures = np.array([[30,32,35],
                         [28,30,33],
                         [25,27,29],
                         [35,37,40]])

#find days with any temperature > 35
temperatures[np.any(temperatures>35, axis=1)]

array([[35, 37, 40]])

In [47]:
#increase all temperatures <=30 by 2
temperatures[temperatures<=30] += 2
temperatures

array([[32, 32, 35],
       [30, 32, 33],
       [27, 29, 31],
       [35, 37, 40]])

In [46]:
#average temperature per day
np.mean(temperatures, axis=1)

array([32.33333333, 30.33333333, 27.        , 37.33333333])

In [48]:
scores = np.array([65,82,90,78])

In [49]:
np.max(scores)

np.int64(90)

In [50]:
np.argmax(scores) #to find the index of maximum number

np.int64(2)

In [51]:
a = np.arange(1,4)
a

array([1, 2, 3])